version: 2

jobs:
  test-node8:
    working_directory: ~/tf2pickup
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Bootstrap Packages
          command: yarn run bootstrap
      - run:
          name: Lint
          command: yarn run lint
      - run:
          name: Test
          command: yarn run test
      - run:
          name: Build packages
          command: yarn run build

workflows:
  version: 2

  test:
    jobs:
      - test-node8
