version: 2

jobs:
  lint:
    working_directory: ~/tf2pickup
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Lint
          command: yarn run lint

  flow:
    working_directory: ~/tf2pickup
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Flow
          command: yarn run flow

  test:
    working_directory: ~/tf2pickup
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Test
          command: yarn run test

  build:
    working_directory: ~/tf2pickup
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Build
          command: yarn run build

workflows:
  version: 2

  test:
    jobs:
      - lint
      - flow
      - test
      - build
